Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/tasks/**/*'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - 'group'
    - 'describe'
    - 'before'
    - 'context'
    - 'resource'
    - 'get'
    - 'example_request'
    - 'feature'

Metrics/ModuleLength:
  Enabled: false

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: '#consistent-string-literals'
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: >-
                 Add the frozen_string_literal comment to the top of files
                 to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false
