language: ruby
rvm: 2.3.4
os: linux
env: RAILS_ENV=test
script:
  - bundle exec rspec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
